### ISSUE TITLE
db overwrites parameters

### ISSUE THREAD

**Issue by ConnyOnny** [RalfJung/lilass#5] opened 2016-04-10 22:10 UTC
When there is a known config for a setup in the database and then you call `lilass -i` it loads the database setup instead of just using the internal screen and switching off everything else.

You can use `lilass -i --no-db` as a workaround.

**Comment by RalfJung** [comment] 2016-04-11 07:04
Yes, that is behavior as intended -- and described as such in the README. `-i`, `-e` and `-r` only take effect if the screen is not yet known. As you said, you can avoid loading the DB (and hence force those options to take effect) by passing `--no-db`.

So, please describe the expected behavior, because so far I see no bug here :)

**Comment by ConnyOnny** [comment] 2016-04-13 10:29
The expected behaviour for me would be that command line parameters take precedence over config files and a display history file, by default.

**Comment by RalfJung** [comment] 2016-04-13 10:52
You mentioned yourself in the original code you wrote that there is a need for a mode where we use the DB if the screen is known, and use some default configuration if the screen is not known. The `-i`/`-e`/`-r` switches are exactly what we need for that, it'd be weird to duplicate them.

What is debatable is the default: `--with-db` or `--without-db` (currently called `--no-db`). Certainly we want `--with-db` to be the default if the UI starts. One possible solution would be to make the default depend on whether `-i`/`-e`/`-r` is present: With such an option, default to `--without-db`; otherwise, default to `--with-db`. However, that seems a little "too clever" to me.

Any ideas?

**Comment by RalfJung** [comment] 2016-04-26 11:28
Closing this for now. This bug is about changing the intended behavior. I can reopen this once there is some clear idea of why the current user story / intended behavior is sub-optimal and what we want to achieve instead.

**Closed as completed by RalfJung** 2016-04-26 11:28 UTC
